name: Build Windows 32-bit & 64-bit

on:
  push:
    branches: [main, release]
  pull_request:
    branches: [main]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install NSIS
        run: choco install nsis -y

      - name: Compile Windows 64-bit Installer
        run: |
          cd desktop/windows
          makensis /DARCH=x64 quantum-browser.nsi

      - name: Compile Windows 32-bit Installer
        run: |
          cd desktop/windows
          makensis /DARCH=x86 quantum-browser.nsi

      - name: Upload Windows Installers
        uses: actions/upload-artifact@v4
        with:
          name: quantum-browser-windows
          path: desktop/windows/output/*.exe
